name: Checkout

on: [push, workflow_dispatch]

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Generate config.json from secrets
        run: |
          cat > config.json << EOF
          {
            "APP_TITLE":         "${{ secrets.APP_TITLE }}",
            "AW_REPORTSUITE_ID": "${{ secrets.AW_REPORTSUITE_ID }}",
            "AW_USERNAME":       "${{ secrets.AW_USERNAME }}",
            "AW_SECRET":         "${{ secrets.AW_SECRET }}"
          }
          EOF
          echo "config.json created!"

      - name: List files
        run: ls -l config.json
